### ISSUE TITLE
Plot axis tick labels are clipped

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/windex#12]
![image](https://github.com/JamesBremner/windex/assets/2046227/9bc77a45-cfe0-45f0-9e14-884a76bc7ddc)

**Comment by JamesBremner** [comment]
![image](https://github.com/JamesBremner/windex/assets/2046227/316f014d-7db2-4900-973e-66f72c574cce)

**Comment by drmcnelson** [comment]
Looks nice,  Thank you. 

Aside,  is there a way to select the font size?  (I can find your mod and build on that, but maybe you did it already)

Will pull the new code

**Comment by JamesBremner** [comment]
Please make testing of bug fixes a very high priority.  If there is a problem, it is so much easier to work on code when it is fresh in mind.  Ideally a bug fix should be tested within 2 hours during normal working hours, 24 hours otherwise.

**Comment by drmcnelson** [comment]
it is good thank you, and it looks nice.    I am testing a lot actually, did not realize you were waiting on this

**Comment by JamesBremner** [comment]
If an issue is assigned to you, it means that the person doing the assignment is waiting for you to do something.  The label, 'question' or 'test' tells you what sort of thing.

**Comment by drmcnelson** [comment]
ok, anyway it is done.  Do I need to click something?

**Comment by JamesBremner** [comment]
Yes.  Close the issue.

( maybe the close button is hidden from you because you are not a collaborator?  If so then all you can do is an unambiguous request to close in a comment )

Closing for you.
