### ISSUE TITLE
Mouse events, question

### ISSUE THREAD

**Issue by drmcnelson** [JamesBremner/windex#14]
Hi,

In the plot, can I set handlers for mouse events?

I am thinking to  display the current mouse position in user coordinates

**Comment by JamesBremner** [comment]
No.

To provide this functionality requires changes to wex::plot::dragExtend()

**Comment by JamesBremner** [comment]
Please remember to label your questions and assign the issue to me.

**Comment by JamesBremner** [comment]
Proposal:

```C++
 //   enable/disable cursor tracking, default is enable, disabled if not called
void cursorTracking( bool f )

 //cursor position in user co-ords.  DBL_MAX,DBL_MAX if cursor tracking disabled or left mouse button down
std::pair<double,double> cursor() 

 //register cursor movement handler
void cursorHandlerRegister( std::function<void(std::pair<double,double> f) 
```

**Comment by drmcnelson** [comment]
If tracking disabled, maybe not call the handler?

**Comment by JamesBremner** [comment]
Modified my initial answer https://github.com/JamesBremner/windex/issues/14#issuecomment-1946614264

**Comment by drmcnelson** [comment]
I realized later, perhaps you meant that when the mouse tracking is disabled, you send one final packet to signal it is disabled?   I think the used can keep track of the fact that they disabled it.

Another point, "on further thought":

Maybe the cleanest, simplest, most efficient and most general approach would be to return the internal coordinates.   I think you already have a function for converting pixel coordinates to user coordinates.   So, the user might as well be responsible for that step.


I am out for the rest of the day, and then I have to do some work to support my collaborator.  Back in the cockpit tomorrow.

**Comment by JamesBremner** [comment]
>  would be to return the internal coordinates. 

This is what I am doing.  Please look at the code I posted, or build and run the demo.

**Comment by drmcnelson** [comment]
I just tested it,  it's amazing.  It looks great and it's super responsive. 

 Thank you,  nicely done, really.

**Comment by drmcnelson** [comment]
Oops, the grid and xaxis labels are mangled.   There is now one x grid line and one x tic mark label.

The axis is mangled with or without the mousetracking event code inserted into the program

![image](https://github.com/JamesBremner/windex/assets/38619857/b5e2ea61-8ac3-4f34-89d9-84bc7aeb40cd)
