### ISSUE TITLE
Text overlaid onto plot?

### ISSUE THREAD

**Issue by drmcnelson** [JamesBremner/windex#15]
Hi

Is there a way to write and update text at a specified location inside the plot area?

(I see there is a text box, but is that the way to do it?)

Thank you

**Comment by JamesBremner** [comment]
I do not know what "text box" refers to.  There is no such widget in windex. ( Seems sometimes you make up your own private name for things.  Not helpful! )

Guessing you mean a label?

You add a label to a plot in exactly the same way you add a label to anything else.

```C++
wex::plot::plot &thePlot = wex::maker::make<wex::plot::plot>(fm);
wex::label &plotLabel = wex::maker::make<wex::label>(thePlot);
plotLabel.move(100, 100, 130, 20);
plotLabel.bgcolor(0xFFFFFF);
plotLabel.text("this is a plot label");
...
thePlot.update();
```

![image](https://github.com/JamesBremner/windex/assets/2046227/4ec363cf-f605-46de-90dc-c1c8a38b5b08)

**Comment by drmcnelson** [comment]
Interesting, when i create the label in the class it does not appear, when I create it inside the resize(), it appears.

Probably my bug.

**Comment by drmcnelson** [comment]
How do I set the color of the text?

**Comment by JamesBremner** [comment]
You need to create the label as a child of the plot instance.  See the code I posted above.

**Comment by drmcnelson** [comment]
I did, I figured it out, see my other message.  The bgcolor() has to be set again in the event handler.

It took about 2 hours of iteration, to discover what was going on.

**Comment by JamesBremner** [comment]
> It took about 2 hours of iteration, to discover what was going on.

That was because you refused to look at the sample code I posted.
