### ISSUE TITLE
Better, but still some grid issues.

### ISSUE THREAD

**Issue by drmcnelson** [JamesBremner/windex#16]
Hi,

Please take a look at the right end of the x axis.  There are two values displayed.  Maybe one is from the box and the other from the grid.

The second graph is after zooming to the data.  It seems the initial ymax value is not correct.

In both of these, it would be nice to be able to label the axes,  xlabel = "wavelength", ylabel = "volts" for example

![Screenshot from 2024-02-15 11-57-04](https://github.com/JamesBremner/windex/assets/38619857/c75e4fe3-96aa-47ee-9c21-9c777cd7fe14)

![Screenshot from 2024-02-15 11-54-13](https://github.com/JamesBremner/windex/assets/38619857/06b67692-e5cb-4953-97ed-e57385d882e5)

**Comment by JamesBremner** [comment]
Shopping list!

Always one per issue, please.

**Comment by JamesBremner** [comment]
Closing shopping list

**Comment by drmcnelson** [comment]
Yes, I am sorry for that.  Stream of consciousness
