### ISSUE TITLE
Grid, errant xmax label

### ISSUE THREAD

**Issue by drmcnelson** [JamesBremner/windex#17]
Okay, here is a single issue.

Please see the graph below.  Notice there are two labels at x max, and, they are different.

For further diagnostics of this same issue,  the second graph shows that with zoom there are still two distinct xmax labels.

![Screenshot from 2024-02-15 11-54-13](https://github.com/JamesBremner/windex/assets/38619857/c60d1e6b-bdc2-444f-aab7-43a4c24405ae)

![Screenshot from 2024-02-15 11-57-04](https://github.com/JamesBremner/windex/assets/38619857/eaee919e-b2c3-4d35-90a1-081b208032f3)

**Comment by JamesBremner** [comment]
I cannot reproduce this, neither with the windex demo or the spectrum plotter.

Where is your code?

**Comment by JamesBremner** [comment]
Are you using `XValues()`?

https://jamesbremner.github.io/windex/classwex_1_1plot_1_1plot.html#ae8aa737cb576eb4f71f68fabb6233434

**Comment by JamesBremner** [comment]
Reproducible if I enable the grid

![image](https://github.com/JamesBremner/windex/assets/2046227/6f30d06f-7c9f-4e95-a521-fe93bfa15edc)

**Comment by drmcnelson** [comment]
Yes,   that is exactly the scenario

**Comment by JamesBremner** [comment]
>I tried to attach the source code as a file, that doesn't work.

Should work if you zip it.

Anyway, a link to your repo would be more convenient

**Comment by drmcnelson** [comment]
Okay, here is the "work in progress".    I am working on it in a vbox,  w11 guest, on a fedora desktop .

[SpectrometerWindex2_240215_1403.zip](https://github.com/JamesBremner/windex/files/14301252/SpectrometerWindex2_240215_1403.zip)

**Comment by drmcnelson** [comment]
It is good, sorry, I did not realize it was still open.

**Comment by JamesBremner** [comment]
It was assigned to you in test for 26 hours.

At least once every working day you should check for any issues assigned to you in any repo by going to https://github.com/issues/assigned

If you find any labelled test, they should be your first priority.
