### ISSUE TITLE
Y axis scaling error

### ISSUE THREAD

**Issue by drmcnelson** [JamesBremner/windex#18]
Graphing a data, the routine finds aberrant yaxis limits.   axisYminmax() may be malfuntioning as well

The three images following are
1)  Diagnostic report showing the min and max y values ascertained directly from the data. 
2)  The graph as initially displayed, notice ymin is good, ymax is not correct and not labeled as well. 
3)  After a zoom, we see the data is actually good and as described in the first screen capture.

The data is submitted to the graphics api as follows:
```
    if (currentFrame && currentFrame->hasdata && !currentFrame->graphed)
    {
        //diagnostic
        float ymax, ymin;
        double *d = currentFrame->data;
        ymax = d[0];
        ymin = d[0];
        for (int n=0; n < currentFrame->length; n++, d++) {
            if(*d>ymax) ymax = *d;
            if(*d<ymin) ymin = *d;
        }
        printf( "first data %g, %g\n", ymin,ymax);
        //end diagnostic

        std::vector<double> v(currentFrame->data,currentFrame->data+currentFrame->length);
        t1.set(v);
        currentFrame->graphed = true;
    }
```

![Screenshot from 2024-02-15 14-26-32](https://github.com/JamesBremner/windex/assets/38619857/95160c58-981a-4f0a-a752-43a7a52d2dae)

![Screenshot from 2024-02-15 14-22-09](https://github.com/JamesBremner/windex/assets/38619857/713e8d27-1ee9-4c26-80ac-f84399214e0c)

![Screenshot from 2024-02-15 14-31-43](https://github.com/JamesBremner/windex/assets/38619857/66f60b94-f4e9-4a26-a903-c1caca6ad107)

**Comment by drmcnelson** [comment]
Here is the fix, see the line inserted at the bottom of set().  That becomes line 130 in plot2d.h

```
        class trace
        {
        public:
            /** \brief set plot data
                @param[in] y vector of data points to display

                Replaces any existing data.  Plot is NOT refreshed.
                An exception is thrown when this is called
                for a trace that is not plot or scatter type
            */
            void set(const std::vector<double> &y)
            {
                if ((myType != eType::plot) && (myType != eType::scatter))
                    throw std::runtime_error("plot2d error: plot data added to non plot/scatter trace");

                myY = y;
                myLastValid = myY.size() - 1;

            }

```

**Comment by drmcnelson** [comment]
BTW, it is really starting to look quite nice
Have to think about the cursor move capture

**Comment by JamesBremner** [comment]
The attribute `myLastValid`  keeps track of the end of the circular bufffer used by the real time trace.  The other traces should ignore it.  

This is an error in `wex::trace::bounds()`

**Comment by drmcnelson** [comment]
okay, i'll try it.

**Comment by drmcnelson** [comment]
Okay, it is good.  I see you fixed it with minmax,  in other words  lastValid has meaning for realtime traces.

**Comment by drmcnelson** [comment]
it is good, means I tried it, it works.  Thank you

**Comment by JamesBremner** [comment]
> in other words lastValid has meaning for realtime traces.

mmm?  That is what I just said https://github.com/JamesBremner/windex/issues/18#issuecomment-1947285620
