### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alecmus** [JamesBremner/windex#2]
Interesting project. Could you kindly consider adding a license to the repo. According to the [licensing guidelines](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) _"without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work"_.

**Comment by JamesBremner** [comment]
Done
