### ISSUE TITLE
Button decoration, color, bg, bold?

### ISSUE THREAD

**Issue by drmcnelson** [JamesBremner/windex#20]
Hi

Is there a way to set the background text colors for a button?   Can the font be set for a single button?

Thank you

**Comment by JamesBremner** [comment]
Take a look at the docs.

![image](https://github.com/JamesBremner/windex/assets/2046227/a2b55b4e-5986-4d99-8cfb-5eff8a40f0db)

Scroll down for font manipulation methods.

**Comment by drmcnelson** [comment]
Oh, I see, those are inherited.   Got to remember to read the fine print.

That was actually the question, using those from the button, only effects the button, yes?

**Comment by drmcnelson** [comment]
How about the color of the text?  There seems to be no color() in gui.

**Comment by JamesBremner** [comment]
Please test #22
