### ISSUE TITLE
Label loses bgcolor on move.

### ISSUE THREAD

**Issue by drmcnelson** [JamesBremner/windex#21]
Inside a resize event, it is necessary to both move() the label, and also, call bgcolor(), as in the following.  On a dark background, commenting out the line that sets the bgcolor() makes the button effectively invisible

```
 myForm.events().resize(
        [&](int w, int h)
        {
           . . . 

            plotLabel.move(LBLX, LBLTOP, LBLWIDTH, LBLHEIGHT);
            plotLabel.bgcolor(LBLBGCOLOR);

            thePlot.update();

            myForm.update();
        });

```

**Comment by JamesBremner** [comment]
You are going at this in the wrong way

A label MUST be creates as a child of the plot instance.  So, then, it will move along with the plot and all its other children.

Please, please, please look at the sample code I posted at https://github.com/JamesBremner/windex/issues/15#issuecomment-1948488363

**Comment by drmcnelson** [comment]
I did that.

```

class cGUI
{
public:
    cGUI();
    void run();

private:
    wex::gui &myForm;
    wex::label &myPortlb;
    // wex::editbox &myPorteb;
    // wex::button &myConnectbn;
    //wex::com &myTalker;
    wex::button &myConsoleBn;
    wex::button &myLastBn;
    wex::button &myNextBn;
    wex::button &myPrevBn;
    wex::button &myFirstBn;
    wex::plot::plot &thePlot;
    wex::plot::trace &t1;
    wex::timer *myPlotTimer;
    wex::label &plotLabel;

    void ConstructPlot();

};

cGUI::cGUI()
    : myForm(wex::maker::make()),
    myPortlb(wex::maker::make<wex::label>(myForm)),
    myConsoleBn(wex::maker::make<wex::button>(myForm)),
    myLastBn(wex::maker::make<wex::button>(myForm)),
    myNextBn(wex::maker::make<wex::button>(myForm)),
    myPrevBn(wex::maker::make<wex::button>(myForm)),
    myFirstBn(wex::maker::make<wex::button>(myForm)),
    thePlot(wex::maker::make<wex::plot::plot>(myForm)),
    plotLabel(wex::maker::make<wex::label>(thePlot)),
    t1(thePlot.AddStaticTrace())
{

```

**Comment by JamesBremner** [comment]
That looks correct, as far as it goes  Now you need to call plotLabel.move() once to set its size.  

![image](https://github.com/JamesBremner/windex/assets/2046227/bf461609-69ac-4aa5-8b3c-e454ba2d28f0)

After this it will move along with the parent.

**Comment by drmcnelson** [comment]
Yes, i did that, and it does.  Thank you.   The bgcolor() is lost nonetheless.

**Comment by JamesBremner** [comment]
> The bgcolor() is lost nonetheless.

I cannot reproduce that

![image](https://github.com/JamesBremner/windex/assets/2046227/28073d26-bd1d-449c-95bf-85c01d630273)

![image](https://github.com/JamesBremner/windex/assets/2046227/8a847481-a242-4beb-9a24-f448f4d64639)

**Comment by drmcnelson** [comment]
okay, maybe its my bug,  will check on it.

Meanwhile, I decided to fit the label to the length of the string, dynamically.  With the white background, it looks a little more professional.

**Comment by drmcnelson** [comment]
Here it is so far. 

![image](https://github.com/JamesBremner/windex/assets/38619857/b38a5e6a-a035-4698-958d-8b2f5e6d4863)

And here is the console window that I use for the moment for testing.  

![image](https://github.com/JamesBremner/windex/assets/38619857/4e9cf375-e1a4-416b-8096-7131fe304fbb)

**Comment by drmcnelson** [comment]
it would be nice to pick up a carriage return in the edit box, but the send button is fine for now.

Too much time in decorating, I have to finish the rest of the buttons,  I plan to add a property grid, a run/stop, a save to disk, nd maybe a menu.  The buttons next to the console are for scrolling through the buffer ring.

I ran it at 100/sec, it keeps pretty nicely.  Maybe better than the python gui.

**Comment by JamesBremner** [comment]
> it would be nice to pick up a carriage return in the edit box

As stated in the docs:  

![image](https://github.com/JamesBremner/windex/assets/2046227/94f706c4-a961-45df-8c05-4253f096431b)


Looking down one line, you will find

![image](https://github.com/JamesBremner/windex/assets/2046227/b5f4f694-60da-4191-a3a3-0da718278400)
