### ISSUE TITLE
Text Color

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/windex#22]
requested in #20 

> How about the color of the text? There seems to be no color() in gui.

**Comment by JamesBremner** [comment]
```C++
    wex::label &plotLabel = wex::maker::make<wex::label>(thePlot);
    plotLabel.move(100, 100, 130, 20);
    plotLabel.bgcolor(0xFFFFFF);
    plotLabel.textColor(0x0000FF);
    plotLabel.text("this is a plot label");
```
![image](https://github.com/JamesBremner/windex/assets/2046227/2944cb81-812e-4caa-aeda-19216102eec4)

**Comment by drmcnelson** [comment]
Perfect, thank you

**Comment by drmcnelson** [comment]
Very nice, works for button and label.  Thank you.
