### ISSUE TITLE
Plot X grid lines misaligned

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/windex#23]
![image](https://github.com/JamesBremner/windex/assets/2046227/25ede738-a0e6-44b0-999a-8ef3de12da67)

**Comment by JamesBremner** [comment]
![image](https://github.com/JamesBremner/windex/assets/2046227/af7b12da-79fa-469f-80ca-dfb783789637)

**Comment by JamesBremner** [comment]
Reported in #14

> Oops, the grid and xaxis labels are mangled.   There is now one x grid line and one x tic mark label.
> 
> The axis is mangled with or without the mousetracking event code inserted into the program

![image](https://github.com/JamesBremner/windex/assets/38619857/b5e2ea61-8ac3-4f34-89d9-84bc7aeb40cd)

**Comment by JamesBremner** [comment]
I cannot reproduce this.  Can you?

**Comment by JamesBremner** [comment]
Cause: XValues() mishandles non-zero values for the 1st parameter

**Comment by drmcnelson** [comment]
Seems to work okay

**Comment by drmcnelson** [comment]
but, I am about to get your lastest version.

**Comment by JamesBremner** [comment]
I have refactored the X scaling plot code so that it is easier to maintain.  Please test with latest version.

**Comment by drmcnelson** [comment]
Okay,  the graphs are noticeably faster.   The zoom feature however, is not working.  And there is a redraw on cursor motion that seems pretty disruptive.   Both phenomena are seen in the initial graph displayed in the simulator.

I am going to upload my current application code to the repo we setup in my account.     I have been doing some code facvtoring too.   I want to move towards isolating the instrument specific code to one file, and perhaps, convert it to a class to represent the spectrometer with a standard set of functions that are invoked from the gui.

**Comment by drmcnelson** [comment]
The new SpectroWindex code has been uploaded.

**Comment by drmcnelson** [comment]
I think this issue can be closed, it works good.
