### ISSUE TITLE
Scaling broken in recent commits

### ISSUE THREAD

**Issue by drmcnelson** [JamesBremner/windex#28]
Hi,

The commits since 2/26 broke something.

Here are images as of 2/26 and after pulling the current version just now.   The zoom and autoscale seem to bother be broken.

Regards
M

![Screenshot from 2024-02-28 14-27-50](https://github.com/JamesBremner/windex/assets/38619857/b6bfb182-42d4-4289-8775-af5f56ccb9e2)

![Screenshot from 2024-02-28 14-31-04](https://github.com/JamesBremner/windex/assets/38619857/210a75dd-cd06-47a7-9a8d-76c92f5cad43)

**Comment by JamesBremner** [comment]
Please check that you are using the latest version.  The windex history should look like this:

![image](https://github.com/JamesBremner/windex/assets/2046227/c1b58501-d051-4f8a-a0d0-c4e5d8caa27f)

**Comment by JamesBremner** [comment]
In general, it is not helpful to talk about "recent commits"  Best is to specify in a bug report the actual commit that you are using, like this https://github.com/JamesBremner/windex/commit/084282b386bfa71ffc3ef041446e6a4f6e890963

**Comment by JamesBremner** [comment]
>  I am giving it a vector with NANs

I would not expect that to work.  What would you expect to see if all that data were NANs?

**Comment by drmcnelson** [comment]
Okay,  but the scaling is broken with normal data also.

**Comment by drmcnelson** [comment]
I dropped back to the version for 2/26 in the meantime.

**Comment by JamesBremner** [comment]
> version for 2/26 

That is meaningless.  Use the commit link.

**Comment by JamesBremner** [comment]
Please explain how to reproduce the problem

**Comment by drmcnelson** [comment]
I am bogged down in something else at the moment.  Will get back to it later or tomorrow, apologies

**Comment by drmcnelson** [comment]
Okay, I will try to give you a more complete and specific description tomorrow.

BTW, I did not update my copy of boost, could that be the source of the problem?

**Comment by drmcnelson** [comment]
Now I am compiling against the current boost, and the current windex.   As noted in our spectrowindex-test, the problem seems related to not using autofit or setfitscale first, or maybe some interaction with having used setXValues

**Comment by JamesBremner** [comment]
Please describe the problem and how I can reproduce it.

When I build and run the simulator, the scaling looks just fine  https://github.com/drmcnelson/SpectroWindex-Testing/issues/11#issuecomment-1976621873

**Comment by drmcnelson** [comment]
Done, works well
