### ISSUE TITLE
setFixedScale(xmin,xmax,ymin,ymax), does not work

### ISSUE THREAD

**Issue by drmcnelson** [JamesBremner/windex#30]
The following does not change the displayed graph limits

                   thePlot.setFixedScale(SpectrometerSettings.xmin,
                                          SpectrometerSettings.xmax,
                                          SpectrometerSettings.ymin,
                                          SpectrometerSettings.ymax);

                   thePlot.update();
  
But, the follow does work well,

                    thePlot.axisYminmax(SpectrometerSettings.ymin,
                                        SpectrometerSettings.ymax);

                   thePlot.update();

The latter followed by the former, also does not change x axis, though the y axis is changed of course.

**Comment by JamesBremner** [comment]
There are 4 scale states and 5 events that cause state changes.

The state machine is

| Event | Prev State | Next State
|---|---|---|
start | * | fit
zoom | fit | fitzoom
zoom | fix | fixzoom
unzoom |  fitzoom | fit
unzoom | fixzoom | fix
fix | fit | fix
unfix | fix | fit

All other event / prev state combinations are ignored silently

Event generators

| User | App Code | Event
|---|---|---|
| start app | - | start
| drag & drop | zoom() | zoom
| right mouse click | unzoom() | unzoom
| - | setFixedScale() | fix
| - | unsetFixedScale() | unfix

**Comment by drmcnelson** [comment]
Do you want me to test something now?

**Comment by JamesBremner** [comment]
Yes.  That is why I assigned this issue to you, labelled test.

**Comment by drmcnelson** [comment]
Plot seems to have lost autoFit() and axisYminmax()

g++ -c SpectrometerWindex2.cpp -I../windex/include -I../../code_ext/boost/boost_1_84_0 -g -static -o SpectrometerWindex2.o
SpectrometerWindex2.cpp: In member function 'void cGUI::ConstructPlot()':
SpectrometerWindex2.cpp:424:13: error: 'class wex::plot::plot' has no member named 'autoFit'
  424 |     thePlot.autoFit();
      |             ^~~~~~~
SpectrometerWindex2.cpp: In lambda function:
SpectrometerWindex2.cpp:438:29: error: 'class wex::plot::plot' has no member named 'autoFit'
  438 |                     thePlot.autoFit();
      |                             ^~~~~~~
SpectrometerWindex2.cpp:448:29: error: 'class wex::plot::plot' has no member named 'axisYminmax'
  448 |                     thePlot.axisYminmax(SpectrometerSettings.ymin,
      |                             ^~~~~~~~~~~
mingw32-make: *** [makefile:22: SpectrometerWindex2.o] Error 1

**Comment by JamesBremner** [comment]
Correct.  Both are now redundant and so removed.

The plot defaults to auto fit ( see documentation of state machine above ).

 To set the fixed limits of the Y-axis, use setFixedScale

**Comment by drmcnelson** [comment]
Great, how to i set it back to auto fit?

**Comment by drmcnelson** [comment]
Oh I see, setFitScaleScale()

**Comment by JamesBremner** [comment]
That's a typo.  It should be simply 'setFitScale()'  

NYI.  I will add it.

**Comment by drmcnelson** [comment]
There is an algorithm as "nice limits" or something similar, dating back to the 80's and maybe ncar.   Do you know it?

**Comment by drmcnelson** [comment]
Okie dokie that;s pretty messed up.  Will upload my current code to the Spectro Windex test repo

Here is what the demo looks like, it sort-of hands for a moment and then the graph appears.

The second image is the actual spectrometer, this one just hangs, the buttons don't respond


![image](https://github.com/JamesBremner/windex/assets/38619857/f95febf5-bb85-4559-a022-ae0370591f4e)


![image](https://github.com/JamesBremner/windex/assets/38619857/d7e516a0-07fa-4a21-9598-1dc35fd59439)

**Comment by JamesBremner** [comment]
> Here is what the demo looks like, it sort-of hands for a moment 

I think you mean the simulator, not the demo.  And probably hangs rather than hands.  Please proof read before posting.

When you have your code committed, assign this back to me.

**Comment by drmcnelson** [comment]
Assign it here, yes?  I am looking for the button that says assign.

**Comment by drmcnelson** [comment]
Sorry, not finding how to do it, the option seems to not appear for me.

**Comment by drmcnelson** [comment]
Okay, in my own repo I have the control to assign it.  I am guessing that is what you meant.

**Comment by drmcnelson** [comment]
Meanwhile, I will try to get some tracking on where it is stuck.

**Comment by drmcnelson** [comment]
Still super broken,   This is built with a fresh "git pull origin".   Oddly it happens with the hardware spectrometer.  The app is unresponsive.   Then after a few minutes it responds a little and hangs again, see second image,.   The simulator is a little better.   It almost seems like it could be some loop in the auto scaler.

![image](https://github.com/JamesBremner/windex/assets/38619857/62c9dd9e-8726-4d10-9062-18a8cbf47100)

![image](https://github.com/JamesBremner/windex/assets/38619857/7fcee4c4-8fd4-4d53-87e5-54189c337224)

**Comment by JamesBremner** [comment]
WHAT?!

You just told me that this worked great

https://github.com/JamesBremner/windex/issues/31#issuecomment-1977143343

**Comment by JamesBremner** [comment]
Reported ( sort of ) in https://github.com/drmcnelson/SpectroWindex-Testing/issues/21

> setFixedScale() fails on Y-axis

**Comment by drmcnelson** [comment]
Done, works well.
