### ISSUE TITLE
Performance and graphics issues in commits since around 2/26

### ISSUE THREAD

**Issue by drmcnelson** [JamesBremner/windex#33]
I thought of a way to be more specific about the issues I am seeing in the current windex

Here are two movies, one compiled with commit   88bd9a46e5dc70e825e4dee6e0aab9d568953cc0, and another with the app compiled with the current version.  

 I recognize that I need to increment my way forward and find exactly which commit this starts happening in. 

Old windex:

https://github.com/JamesBremner/windex/assets/38619857/75b1461c-adf0-468f-a5d0-f84a16684851

Current windex:

https://github.com/JamesBremner/windex/assets/38619857/b48a4b8b-6796-40a7-9abc-ac70fed9b773

**Comment by JamesBremner** [comment]
I took a look at your video.  I do not know what I am supposed to be looking for.  Is the video of a simulator run?  What is happening that should not be happening?  What is not happening that should be happening?

Please post a single screenshot of the GUI and describe what is wrong with it, and the steps required to get to that point using the simulator.  Then I will be able to reproduce whatever this problem is.

**Comment by drmcnelson** [comment]
Notice in the build with the list commit from 2/26,
   
   A)   The graph appears right away and all of the control actions are prompt and smooth.
   B)   Cllcking run, it promptly receives new data and draws a new graph. 
   C)   Changing to clocked data, and clicking run, it immediately receives the clocked frames and draws the graphs

   So everything is good


In the build with the current windex:

   A)  It draws the y axis, then hangs for a long while, and then finally, draws the x axis and data.

   B)  Clicking run, again, it takes a long time to draw the next graph
   
    C)   Starting clocked data, as above, it simply hangs and never comes back.   I had to use Ctrl-C from the terminal window.l

**Comment by JamesBremner** [comment]
OK, I can understand that.

There were 4 commits on 2/26.  Can you be more specific about which one?

![image](https://github.com/JamesBremner/windex/assets/2046227/f393b0e6-e2d5-469e-8a55-72a523c9737a)

**Comment by drmcnelson** [comment]
The one that works is 88bd9a4,  "Merge pull request https://github.com/JamesBremner/windex/pull/27 from drmcnelson/patch-2"

I was thinking about why the simulation does not expose the issue as severely as the actual hardware spectrometer.    The simulation is probably not threaded, or even if it were, it is still not as independent as actual hardware.   Still we might try threading it to see if it becomes a more realistic challenge.

**Comment by JamesBremner** [comment]
Can this problem be reproduced in the simulator?  If not, then you are on your own - it is nothing to do with windex.

**Comment by drmcnelson** [comment]
The simulator becomes more sluggish since then also, though not as severe.   As I mentioned above, it might be possible to make it more taxing by threading it.   Will look into it.

**Comment by drmcnelson** [comment]
I just confirmed, that yes, the simulator does it too.  

Compiled with the earlier commit:  click run, the response is immediate.

Compiled with the current commit: click run and there is a few seconds with nothing happening.

**Comment by drmcnelson** [comment]
Well, I did not noticed, I have been working on the save to file operation.   Will try it.   I might be doing another compile soon.

**Comment by drmcnelson** [comment]
Building with -O2, no -g, and it still pauses, for both simulator and spectrometer,.  The pause for the spectrometer is very long.  When I clock on setup, it takes a long time to open the window, and after setting autoscale control, it takes even longer before it finally displays something, a minute or at least.   Meanwhile it displays the "not responding" meassage in the title bar for the window.

**Comment by JamesBremner** [comment]
> The pause for the spectrometer is ...

I cannot reproduce this since I cannot run the non simulator app.  So you are on your own there

I have explained why the simulator is sluggish to start in https://github.com/drmcnelson/SpectroWindex-Testing/issues/23 and https://github.com/drmcnelson/SpectroWindex-Testing/issues/24

**Comment by drmcnelson** [comment]
Okay, will try some of this tomorrow.

**Comment by JamesBremner** [comment]
> The startup is better with the optimization and cleaning up the other things you mentioned. 

Good.  The remaining delay on startup is caused by the spectrometer setup which takes a full 4 seconds.

> The huge delay in drawing the trace remains. The delay is significant with the simulator

I will look into this if you describe the steps needed to reproduce the problem in the simulator.

**Comment by JamesBremner** [comment]
See #34

**Comment by drmcnelson** [comment]
Done, works beautifully,  I am going to close it if that is okay with you.
