### ISSUE TITLE
Error in drawing Y-axis grid lines

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/windex#34]
Reported in https://github.com/drmcnelson/SpectroWindex-Testing/issues/28

Currently, the grid lines are drawn using dotted lines.  This is famously slow because it means asking the graphics ship to change the color of individual pixels - which is known to be slow.  If the machine has a cheap graphics chip this is extremely slow.

One solution would be to reduce the number of pixels that are changed, but I think this would make the grid lines less useful.  So, I will draw solid lines ( very fast ) with a thin, faint colored pen.

**Comment by JamesBremner** [comment]
Found that the problem lies elsewhere.  The range of Y-axis values is not being set properly, causing mamy extra gridlines to be drawn to invisible locations - killing the performance.

**Comment by drmcnelson** [comment]
Works well.   Thank you
