### ISSUE TITLE
default file extension seems to not appear in the dialog

### ISSUE THREAD

**Issue by drmcnelson** [JamesBremner/windex#35]
The following code includes a call to set a default file extension, but it does not appear in the dialog

void SaveWindow()
{
    gui &form = maker::make();
    form.move({50, 50, 400, 500});
    form.text("Save");

    wex::filebox fb( form );

    fb.defaultExtension( SPECTRUMDATAFILEEXT );
    
    std::string filename = fb.save();

    if (!strlen(filename.c_str())) {
        printf( "no file specified\n");
    }
    else {
        printf( "save to : %s\n", filename.c_str());
        saveSeries(filename.c_str());
    }

    return;

}

![image](https://github.com/JamesBremner/windex/assets/38619857/9f93360f-49f5-41f2-b57d-4c59cd2aff4d)

**Comment by drmcnelson** [comment]
Further info:    The file is created with the default extension.   So, perhaps what is needed is that my routine needs to call something to set a filter for the listing?

**Comment by drmcnelson** [comment]
Sovled, need to call filter() too.   That takes care of everything, done.

**Comment by JamesBremner** [comment]
> The following code includes a call to set a default file extension, but it does not appear in the dialog

Correct!  That is the way it works.  The file extension is added to whatever the user types into the save dialog.

> When the user of your application specifies a file name without an extension, the [FileDialog](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.filedialog?view=windowsdesktop-8.0) appends an extension to the file name.

https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.filedialog.defaultext?view=windowsdesktop-8.0
