### ISSUE TITLE
Set plot margin sizes

### ISSUE THREAD

**Issue by drmcnelson** [JamesBremner/windex#36]
The desired enhancement, is to set the size of the margin between the plot axes and the edge of the plot area.

Use cases include adding labels to the axes (as distinct from tic labels) in the space outside of the axes and their tic labels

Thank you

**Comment by JamesBremner** [comment]
thePlot.setMarginWidths( 200, 400 );

gives

![image](https://github.com/JamesBremner/windex/assets/2046227/6826179b-b4b3-45f3-b07e-a6b64007b771)

**Comment by drmcnelson** [comment]
Apologies for being out of radio contact, I am deep into a firmware and board bring up.

This looks nice.  Is there a rotation for labels?   In other words, can we place a y axis label that is rotated 90 degrees counter clockwise?
