### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by drmcnelson** [JamesBremner/windex#4]
It looks like a great library.  Thank you.   Could you please provide more specific and complete instructions to build the examples?   Imagine someone who knows c/c++ but  is not familiar with building programs in windows.

**Comment by JamesBremner** [comment]
You write:

>  not familiar with building programs in windows.

>  40 years in scientific software development

Where and how do you usually build your applications?

If you are not familiar with development on windows, I think windex is most probably not a good choice for you :-(

**Comment by JamesBremner** [comment]
```
# Simplified demo makefile
# Use this if you do not need the TCP and COM serial port features

INCS=-I../../include   \
	-I../../../../code_ext/boost/boost1_78
LIBS=-lgdiplus -lgdi32 -lcomdlg32 -lComctl32

demo: ../../demo/demo.cpp 
	g++ -g ../../demo/demo.cpp -o../../bin/demo.exe  $(INCS) $(LIBS)
     
```

Use this from the command line, like this

```
C:\Users\James\code\windex\build\vscode>mingw32-make -f simple_demo_makefile.txt
g++ -g ../../demo/demo.cpp -o../../bin/demo.exe  -I../../include -I../../../../code_ext/boost/boost1_78 -lgdiplus -lgdi32 -lcomdlg32 -lComctl32
```

**Comment by JamesBremner** [comment]
I have added complete build instructions to the wiki at

https://github.com/JamesBremner/windex/wiki/Build-Instructions

**Comment by JamesBremner** [comment]
`../../include/propertygrid.h:4:10: fatal error: boost/property_tree/ptree.hpp: No such file or directory`

You need to install the boost library where the makefile expects it to be, or edit the makefile to let it know where you have installed boost.

Expected directory structure is

```
somepath\code\windex\build\vscode
somepath\code_ext\boost\boost1_78
```

To edit the makefile to look for the boost library somewhere else, edit this line

`	-I../../../../code_ext/boost/boost1_78`

**Comment by JamesBremner** [comment]
Is your build successful now?  Can we close this issue?

**Comment by drmcnelson** [comment]
Okay, it compiled, and the demo works.  Need a couple of tweeks, as follows:

1) The toplevel directory in the boost_1_78 download is boost_1_78_0.   So some renaming and moving is needed to get it set up to match the make file

2)  The bin directory referenced in the make file is missing.  I  did a mkdir ../../bin from the shell open in the vscode directory, and after that the compilation ran.

**Comment by drmcnelson** [comment]
The demo still looks pretty complicated.   is there a simple live plot example?   Thank you

**Comment by JamesBremner** [comment]
> live plot example

Do you mean a real time plot?

To run the real time plot demo:

- run demo
- click plot button
- click real time button

**Comment by JamesBremner** [comment]
No response in three days.
