### ISSUE TITLE
Configure COM input buffer size

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/windex#7]
Requested in #6 

> Calls to set and get the readbuffer size.

**Comment by JamesBremner** [comment]
Assuming you mean the COM input buffer here.

This is done using windows API method `SetupComm`  https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setupcomm

Windex is a thin and transparent wrapper for the windows API, which means you can do this:

```
wex::com &talker(parentWindow);
talker.port("9");
talker.open();
SetupComm( 
    talker.handle(),
    16000,             // input buffer length
    4000 );
```

**Comment by JamesBremner** [comment]
Or you can update and use wex::com::deviceInputBuffer();

**Comment by drmcnelson** [comment]
Great thank you

**Comment by drmcnelson** [comment]
I dont see a close button, i guess you own this one.  But I am okay with closing it.
