### ISSUE TITLE
Feature request, scrolling text output

### ISSUE THREAD

**Issue by drmcnelson** [JamesBremner/windex#8]
This feature request is for a text output box, with a scroll bar, and a method that appends a line of text to the contents of the scroll box, and positions the view to the bottom of the list.

**Comment by drmcnelson** [comment]
The present scroll box seems to require text be entered and positioned manually, or at least that is the way it is shown in the demo.

**Comment by JamesBremner** [comment]
- Create a multiline textbox https://jamesbremner.github.io/windex/classwex_1_1multiline.html
- Add a vertical scroll bar
- When you add a line of text to the multiline, scroll to the bottom

**Comment by JamesBremner** [comment]
> The present scroll box 

There is no such thing. You can add scollbar(s) to any widget, but there is no "scroll box"

**Comment by JamesBremner** [comment]
I think what you are looking for is the list widget

https://jamesbremner.github.io/windex/classwex_1_1list.html

I have changed the scroll demo to show how to use the list widget as you describe

```C++
void ScrollDemo()
{
    // construct top level window
    gui &form = wex::maker::make();
    form.move({50, 50, 400, 400});
    form.text("Scroll demo");

    // construct list
    wex::list &list = wex::maker::make<wex::list>(form);
    list.move(10, 10, 200, 100);
    list.add("this is a demo");
    list.add("line 2 ");
    list.add("line 3");
    list.add("line 4 ");
    list.add("line 5 ");
    list.add("line 6 ");
    list.add("line 7 ");
    list.add("line 8 ");
    list.add("line 9 ");

    wex::editbox &eb = wex::maker::make<wex::editbox>(form);
    eb.move(50, 150, 200, 20);
    eb.text("enter some text");

    wex::button &bn = wex::maker::make<wex::button>(form);
    bn.move(300, 150, 50, 20);
    bn.text("ADD");
    bn.events().click(
        [&]()
        {
            // add text to end
            list.add(eb.text());

            //scroll added text into view
            list.select(list.count()-1);
        });

    form.show();
}
```
